# Generated by Django 5.0.3 on 2024-03-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PDBID", models.CharField(max_length=32)),
                ("UniProtID", models.CharField(max_length=32)),
                ("Sequence", models.CharField(max_length=32)),
                ("img_url", models.CharField(max_length=64, verbose_name="图片路径")),
                ("Description", models.TextField(max_length=64, verbose_name="描述")),
                ("PDB_url", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
                ("email", models.EmailField(max_length=32, verbose_name="邮箱")),
                (
                    "qq",
                    models.CharField(
                        blank=True,
                        default="123",
                        max_length=32,
                        null=True,
                        verbose_name="QQ",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="性别"
                    ),
                ),
                (
                    "work",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="地址"
                    ),
                ),
            ],
        ),
    ]
