# Generated by Django 5.0.3 on 2024-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="Description",
            field=models.TextField(
                blank=True, max_length=64, null=True, verbose_name="描述"
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="PDB_url",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="img_url",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="图片路径"
            ),
        ),
    ]
