# Generated by Django 5.0.4 on 2024-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mainapp", "0003_protein_aminoacids_protein_biologicalprocess_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="Sequence",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Taxonomicidentifier",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
