# Generated by Django 5.0.4 on 2024-05-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mainapp", "0004_alter_protein_sequence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="PDB_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
