# Generated by Django 5.0.4 on 2024-05-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mainapp", "0005_alter_protein_pdb_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="Aminoacids",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="BiologicalProcess",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CATHID",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CATHPDBdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CATHarchitecture",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CATHclass",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CATHrenumdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CATHsupfamily",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CATHtopology",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="CellularComponent",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Classification",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Component",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Description",
            field=models.TextField(
                blank=True, max_length=64, null=True, verbose_name="描述"
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODF",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODH",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODID",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODPDBdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODT",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODX",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODarchitecture",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODdomainID",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ECODrenumdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="ExpressionSystem",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="GOlink",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Gene",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Identifier",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Length",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="MolecularFunction",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Mutation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Orderedlocus",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Organism",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="PDBDOI",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="PDBID",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Primaryaccession",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="PubMed",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SCOPPDBdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SCOPclass",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SCOPfamily",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SCOPfold",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SCOPrenumdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SCOPsupfamily",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SWORDID",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SWORDPDBdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SWORDquality",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="SWORDrenumdelineation",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Strain",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Submittednames",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="Taxonomiclineage",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="UniProtID",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="UniProtentry",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="alpha",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="avgRMSF",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="avggyration",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="beta",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="coil",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="contactchain",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="contaction",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="contactligand",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="contactnucleotide",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="divMM",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="divSE",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="download_link",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="img_url",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="图片路径"
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="nocontact",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="nonredundantdomain",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="nonredundantprotein",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=64, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="电话号码"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="qq",
            field=models.CharField(
                blank=True, default="123", max_length=64, null=True, verbose_name="QQ"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=64, verbose_name="用户名"),
        ),
        migrations.AlterField(
            model_name="user",
            name="work",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="地址"
            ),
        ),
    ]
