# Generated by Django 5.0.4 on 2024-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mainapp", "0006_alter_protein_aminoacids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protein",
            name="Belongstofamilylink",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="protein",
            name="HOGENOM",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
