from django.db import models

# Create your models here.

class User(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=64)
    password = models.CharField(verbose_name="密码", max_length=64)
    email = models.EmailField(verbose_name="邮箱", max_length=64)
    qq = models.CharField(verbose_name="QQ", max_length=64, null=True, blank=True, default="123")
    phone = models.CharField(verbose_name="电话号码", max_length=64, null=True, blank=True)
    sex = models.CharField(verbose_name="性别", max_length=64, null=True, blank=True)
    work = models.CharField(verbose_name="地址", max_length=64, null=True, blank=True)


# # class Record(models.Model):
# class Protein(models.Model):
#     PDBID = models.CharField(max_length=64)
#     UniProtID = models.CharField(max_length=64)
#     Sequence = models.CharField(max_length=64)
#     img_url = models.CharField(verbose_name="图片路径", max_length=64, null=True, blank=True)
#     Description = models.TextField(verbose_name="描述", max_length=64, null=True, blank=True)
#     PDB_url = models.CharField(max_length=64, null=True, blank=True)

class Protein(models.Model):
    PDBID = models.CharField(max_length=64, null=True)
    UniProtID = models.CharField(max_length=64, null=True)
    Sequence = models.CharField(max_length=255, null=True)
    img_url = models.CharField(verbose_name="图片路径", max_length=64, null=True, blank=True)
    Description = models.TextField(verbose_name="描述", max_length=64, null=True, blank=True)
    PDB_url = models.CharField(max_length=255, null=True, blank=True)
    download_link = models.CharField(max_length=64, null=True, blank=True)
    UniProtentry = models.CharField(max_length=64, null=True)
    PDBDOI = models.CharField(max_length=64, null=True)
    PubMed = models.CharField(max_length=64, null=True)
    Classification = models.CharField(max_length=64, null=True)
    Organism = models.CharField(max_length=64, null=True)
    Mutation = models.CharField(max_length=64, null=True)
    Gene = models.CharField(max_length=64, null=True)
    ExpressionSystem = models.CharField(max_length=64, null=True)
    Aminoacids = models.CharField(max_length=64, null=True)
    Length = models.CharField(max_length=64, null=True)
    GOlink = models.CharField(max_length=64, null=True)
    CellularComponent = models.CharField(max_length=64, null=True)
    MolecularFunction = models.CharField(max_length=64, null=True)
    BiologicalProcess = models.CharField(max_length=64, null=True)
    Submittednames = models.CharField(max_length=64, null=True)
    Identifier = models.CharField(max_length=64, null=True)
    Component = models.CharField(max_length=64, null=True)
    Name = models.CharField(max_length=64, null=True)
    Orderedlocus = models.CharField(max_length=64, null=True)
    Taxonomicidentifier = models.CharField(max_length=255, null=True)
    Strain = models.CharField(max_length=64, null=True)
    Taxonomiclineage = models.CharField(max_length=64, null=True)
    Primaryaccession = models.CharField(max_length=64, null=True)
    alpha = models.CharField(max_length=64, null=True)
    beta = models.CharField(max_length=64, null=True)
    coil = models.CharField(max_length=64, null=True)
    ECODdomainID = models.CharField(max_length=64, null=True)
    ECODarchitecture = models.CharField(max_length=64, null=True)
    ECODID = models.CharField(max_length=64, null=True)
    ECODPDBdelineation = models.CharField(max_length=64, null=True)
    ECODrenumdelineation = models.CharField(max_length=64, null=True)
    ECODX = models.CharField(max_length=64, null=True)
    ECODH = models.CharField(max_length=64, null=True)
    ECODT = models.CharField(max_length=64, null=True)
    ECODF = models.CharField(max_length=64, null=True)
    CATHID = models.CharField(max_length=64, null=True)
    CATHPDBdelineation = models.CharField(max_length=64, null=True)
    CATHrenumdelineation = models.CharField(max_length=64, null=True)
    CATHclass = models.CharField(max_length=64, null=True)
    CATHarchitecture = models.CharField(max_length=64, null=True)
    CATHtopology = models.CharField(max_length=64, null=True)
    CATHsupfamily = models.CharField(max_length=64, null=True)
    SCOPPDBdelineation = models.CharField(max_length=64, null=True)
    SCOPrenumdelineation = models.CharField(max_length=64, null=True)
    SCOPclass = models.CharField(max_length=64, null=True)
    SCOPfold = models.CharField(max_length=64, null=True)
    SCOPsupfamily = models.CharField(max_length=64, null=True)
    SCOPfamily = models.CharField(max_length=64, null=True)
    SWORDID = models.CharField(max_length=64, null=True)
    SWORDquality = models.CharField(max_length=64, null=True)
    SWORDrenumdelineation = models.CharField(max_length=64, null=True)
    SWORDPDBdelineation = models.CharField(max_length=64, null=True)
    divSE = models.CharField(max_length=64, null=True)
    divMM = models.CharField(max_length=64, null=True)
    avgRMSF = models.CharField(max_length=64, null=True)
    avggyration = models.CharField(max_length=64, null=True)
    contactchain = models.CharField(max_length=64, null=True)
    contactligand = models.CharField(max_length=64, null=True)
    contaction = models.CharField(max_length=64, null=True)
    contactnucleotide = models.CharField(max_length=64, null=True)
    nocontact = models.CharField(max_length=64, null=True)
    nonredundantprotein = models.CharField(max_length=64, null=True)
    nonredundantdomain = models.CharField(max_length=64, null=True)
    Belongstofamilylink = models.CharField(max_length=64, null=True)
    HOGENOM = models.CharField(max_length=64, null=True)

